#!/usr/bin/env bash
# script that will display information about subdomains.


DOMAIN="$1"
SUB="$2"

function () {

    LINE=$(dig "${SUB}.${DOMAIN}" | grep "$DOMAIN" | tail -1)
    RECORD=$(echo "$LINE" | awk '{print $4}')
    DEST=$(echo "$LINE" | awk '{print $5}')
    echo The subdomain "$SUB" is a "$RECORD" record and points to "$DEST"
}

if [[ -z "$2" ]]
then   
    SUB="www lb-01 web-01 web-02"
    for i in $SUB;
    do
	function "$1" "$i"
    done
else
    sub "$1" "$2"
fi

exit 0
