#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
