#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80

apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.html
sudo sed -i '/server_name _/a \        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4/$1 permanent;\n' /etc/nginx/sites-enabled/default
service nginx restart
