#!/usr/bin/env bash
sudo apt-get update -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8 -y
sudo apt-get upgrade -y
sudo apt-get install haproxy -y

printf %s "frontend firstbalance
            bind *:80
            option forwardfor
            default_backend webservers
        backend webservers
            balance roundrobin
            server 2791-web-01 34.138.71.136:80 check
            server 2791-web-02 34.75.27.207:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
