#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get install haproxy
printf %s "frontend firstbalance
            bind *:80
            option forwardfor
            default_backend webservers
        backend webservers
            mode http
            balance roundrobin
            option forwardfor
            http-request set-header X-Forwarded-Port %[dst_port]
            http-request add-header X-Forwarded-Proto https if { ssl_fc }
            server 2791-web-01 34.138.71.136:80
            server 2791-web-02 34.75.27.207:80
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
