#!/usr/bin/env bash
# that displays listening ports:

#That only shows listening sockets
#That shows the PID and name of the program to which each socket belongs

if "$1";
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
