#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and 9th time prints Hi
i=0
while [ $i -lt 10 ]
do
  echo "Holberton School"
  ((i++))
  if [ $i = 9 ];
  then
  echo "Hi"
  fi
done
