#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

i=0
counter=0

while [ $i -le 59 ]
do
  ((i++))
  
  if [ $i -eq 59 ];
  then
  ((counter++))
  echo "Hour: $counter"
  i=0
  elif [ $counter = 12];
  then
  exit 0
  else
  echo $i
  fi

done
