#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

i=0
j=0

while [ $i -lt 12 ]
do

    echo "Hour: $i"
    while [ $j -lt 59 ]
    do
    echo $j
    ((j++))
    done
    ((i++))
done
