#!/usr/bin/env bash
# This script displays content of the current directory

FILE=./holbertonschool

if test -e "$FILE"; then
    echo "holbertonschool file exists"
    if [ -s "$FILE" ]
    then
        echo "holbertonschool file is not empty"
    else
        echo "holbertonschool file is empty"
    fi
    if test -f "$FILE"; then
        echo "holbertonschool is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
