#!/usr/bin/env bash
# script that configures an Ubuntu server with the below requirements.

cp /etc/hosts ~/hosts.new
# sed -i "s/127.0.0.1/127.0.0.2/p" ~/hosts.new
echo "127.0.0.2 localhosts" > ~/hosts.new
echo "157.240.11.35 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
